<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="TorchSharp" Version="0.107.0" />
    <PackageVersion Include="TorchSharp-cpu" Version="0.107.0" />
    <PackageVersion Include="TorchSharp-cuda-linux" Version="0.107.0" />
    <PackageVersion Include="TorchSharp-cuda-windows" Version="0.107.0" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>
</Project>
