<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>c2_pcg.flowMatchingEval</RootNamespace>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="../c2-pcg.flow-matching-dataloader/c2-pcg.flow-matching-dataloader.csproj" />
    </ItemGroup>

</Project>
